---

- name: Ensure group vmail exists
  group:
    name: vmail
    gid: 5000
    state: present

- name: Ensure user vmail exists
  user:
    name: vmail
    uid: 5000
    group: vmail
    comment: User for virtual mailboxes
    shell: /bin/false
    home: /srv/mail/
    create_home: no
    state: present

- name: Ensure directory for virtual mailboxes exists
  file:
    path: /srv/mail
    state: directory
    owner: vmail
    group: vmail
    mode: 0755

#- name: 'Configure Postfix: Aliases'
#  command: 
#  notify: 'Remap virtual_aliases'
- name: Configure Redis for rspamd
  copy:
    src: etc/redis/rspamd.conf
    dest: /etc/redis/rspamd.conf
    owner: root
    group: redis
    mode: 0640
  notify:
    - restart redis

- name: Ensure user _rspamd is member of group redis
  user:
    name: _rspamd
    groups: redis
    append: yes

- name: Ensure working directory for Redis exists
  file:
    path: /var/lib/redis/rspamd
    state: directory
    owner: redis
    group: redis
    mode: 0750

- name: Enable server redis@rspamd and make sure it is running
  systemd:
    name: redis@rspamd
    enabled: yes
    state: started

- name: Configure rspamd (static config)
  copy:
    src: etc/rspamd/
    dest: /etc/rspamd/
  notify:
    - restart rspamd

- name: Configure DKIM-signing
  template:
    src: etc/rspamd/local.d/dkim_signing.conf.j2
    dest: /etc/rspamd/local.d/dkim_signing.conf
  notify:
    - restart rspamd

- name: Configure spam actions
  template:
    src: etc/rspamd/local.d/actions.conf.j2
    dest: /etc/rspamd/local.d/actions.conf
  notify:
    - restart rspamd

- name: Enable rspamd and make sure it is running
  systemd:
    name: rspamd
    enabled: yes
    state: started

- name: Configure dovecot
  template:
    src: etc/dovecot/dovecot.conf.j2
    dest: /etc/dovecot/dovecot.conf
  notify:
    - restart dovecot

- name: Configure accounts
  template:
    src: etc/dovecot/shadow.j2
    dest: /etc/dovecot/shadow
    owner: dovecot
    group: root
    mode: 0400

- name: Configure mailboxes
  template:
    src: etc/dovecot/users.j2
    dest: /etc/dovecot/users

- name: Ensure that required mailboxes exists
  file:
    path: "{{ item }}"
    state: directory
    owner: vmail
    group: vmail
    mode: 0700
  with_items:
    - "{{ mail_mailboxes | map(attribute='path') | list | unique }}"

- name: Enable dovecot and make sure it is running
  systemd:
    name: dovecot
    enabled: yes
    state: started