---

- include: install.yml
- include: setup.yml
- include: setup-rspamd.yml
- include: setup-ssl-test.yml
  when: "mail_ssl.generate_certificate_for_test | default(false) | bool"
- include: setup-dovecot.yml
- include: setup-postfix.yml
