---
# provides rspamd and clamav-unofficial-sigs
- name: Install repository home:chkpnt:mailserver
  community.general.zypper_repository:
    name: home_chkpnt_mailserver
    repo: https://download.opensuse.org/repositories/home:/chkpnt:/mailserver/15.4/
    state: present
    auto_import_keys: true

- name: Install packages for mailserver
  community.general.zypper:
    name:
      - postfix
      - mailx
      #- postgrey
      - dovecot # openSUSE Leap 42.3: 2.2, openSUSE Leap 15.1: 2.3
      #- amavisd-new
      #- spamassassin
      - rspamd
      - redis
      - unbound # using a local resolver is highly recommended for RBLs
      - clamav
      - clamav-unofficial-sigs
      - acl
    state: present
