---

# provides rspamd and clamav-unofficial-sigs
- name: Install repository home:chkpnt:mailserver
  zypper_repository:
    name: home_chkpnt_mailserver
    repo: 'https://download.opensuse.org/repositories/home:/chkpnt:/mailserver/openSUSE_Leap_15.1/'
    state: present
    auto_import_keys: yes

- name: Install packages for mailserver 
  zypper:
    name:
      - postfix
      - mailx 
      #- postgrey
      - dovecot # openSUSE Leap 42.3: 2.2, openSUSE Leap 15.1: 2.3
      #- amavisd-new
      #- spamassassin
      - rspamd
      - redis
      - unbound # using a local resolver is highly recommended for RBLs
      - clamav
      - clamav-unofficial-sigs
      - acl
      - python2-pyOpenSSL # needed for ansible-module openssl_certificate
    state: present

