---

- name: Initialize variable
  set_fact:
    error_messages: []

- ansible.builtin.import_tasks: install.yml
- ansible.builtin.import_tasks: setup.yml
- ansible.builtin.import_tasks: setup-rspamd.yml
- ansible.builtin.include_tasks: setup-ssl-test.yml
  when: "mail_ssl.generate_certificate_for_test | default(false) | bool"
- ansible.builtin.import_tasks: setup-dovecot.yml
- ansible.builtin.import_tasks: setup-sieve.yml
- ansible.builtin.import_tasks: setup-postfix.yml
- ansible.builtin.import_tasks: setup-apparmor.yml

- name: Messages for your attention
  command: /bin/true
  notify: >-
    {% if error_messages | length == 0 -%}
      print everything alright
    {%- else -%}
      print error_messages
    {%- endif %}
