---

- name: Initialize variable
  set_fact:
    error_messages: []

- include: install.yml
- include: setup.yml
- include: setup-rspamd.yml
- include: setup-ssl-test.yml
  when: "mail_ssl.generate_certificate_for_test | default(false) | bool"
- include: setup-dovecot.yml
- include: setup-postfix.yml
- include: setup-apparmor.yml

- name: Messages for your attention
  command: /bin/true
  notify: >-
    {% if error_messages | length == 0 -%}
      print everything alright
    {%- else -%}
      print error_messages
    {%- endif %}
