---

- name: Ensure openSUSE will not override our config (see /usr/sbin/config.postfix)
  block:
    - lineinfile: # noqa 502
        path: /etc/sysconfig/mail
        regexp: '^MAIL_CREATE_CONFIG='
        line: 'MAIL_CREATE_CONFIG="no"'
    - copy: # noqa 502
        # see /etc/postfix/system/config_postfix, which is called by /usr/lib/systemd/system/postfix.service
        dest: /var/adm/postfix.configured
        content: ""
        force: no

# see /etc/postfix/system/update_postmaps, which is called by /usr/lib/systemd/system/postfix.service
- name: Ensure the maps will be only updated by ansible and not by openSUSE
  lineinfile:
    path: /etc/sysconfig/postfix
    regexp: '^POSTFIX_UPDATE_MAPS='
    line: 'POSTFIX_UPDATE_MAPS="no"'

- name: Configure Postfix
  template:
    src: etc/postfix/main.cf.j2
    dest: /etc/postfix/main.cf
  notify:
    - restart postfix

- name: Configure Postfix (master.cf)
  copy:
    src: etc/postfix/master.cf
    dest: /etc/postfix/master.cf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart postfix

- name: Generate Diffie-Hellman parameters for non-export ciphers (4096 bit)
  command: "openssl dhparam{{ ' -dsaparam' if not (mail_ssl.generate_safe_primes_for_dh | default(true) | bool) else '' }} -out /etc/postfix/dh_4096.pem 4096"
  args:
    creates: /etc/postfix/dh_4096.pem

- name: Generate Diffie-Hellman parameters for export ciphers (512 bit)
  command: "openssl dhparam{{ ' -dsaparam' if not (mail_ssl.generate_safe_primes_for_dh | default(true) | bool) else '' }} -out /etc/postfix/dh_512.pem 512"
  args:
    creates: /etc/postfix/dh_512.pem

- name: Ensure user postfix is member of group _rspamd, so /var/run/rspamd/worker-proxy.socket can be accessed
  user:
    name: postfix
    groups: _rspamd
    append: yes

- name: Configure virtual aliases
  template:
    src: etc/postfix/virtual_aliases.j2
    dest: /etc/postfix/virtual_aliases
  notify:
    - postmap virtual_aliases

- name: Configure virtual mailboxes
  template:
    src: etc/postfix/virtual_mailboxes.j2
    dest: /etc/postfix/virtual_mailboxes
  notify:
    - postmap virtual_mailboxes

- name: Configure transports map
  template:
    src: etc/postfix/transport.j2
    dest: /etc/postfix/transport
  notify:
    - postmap transport

- name: Configure recipient restrictions map
  template:
    src: etc/postfix/recipient_restrictions.j2
    dest: /etc/postfix/recipient_restrictions
  notify:
    - postmap recipient_restrictions
