---

- name: Is AppArmor active?
  block:
    - shell: systemctl is-enabled apparmor.service # noqa 303 305 502
      register: systemstatus_apparmor
    - set_fact: # noqa 502
        apparmor_active: "{{ systemstatus_apparmor.stdout == 'enabled' }}"

- name: Configure AppArmor for dovecot
  copy:
    src: etc/apparmor.d/tunables/dovecot
    dest: /etc/apparmor.d/tunables/dovecot
    owner: root
    group: root
    mode: 0644
  when: apparmor_active
  notify:
    - restart apparmor
