---
- name: Ensure group vmail exists
  ansible.builtin.group:
    name: vmail
    gid: 5000
    state: present

- name: Ensure user vmail exists
  ansible.builtin.user:
    name: vmail
    uid: 5000
    group: vmail
    comment: User for virtual mailboxes
    shell: /bin/false
    home: /srv/mail/
    create_home: false
    state: present

- name: Ensure directory for virtual mailboxes exists
  ansible.builtin.file:
    path: /srv/mail
    state: directory
    owner: vmail
    group: vmail
    mode: "0755"
