---

- name: Ensure directory for global Sieve scripts and companion executables exists
  file:
    path: /srv/mail/.sieve/bin
    recurse: yes
    state: directory
    owner: vmail
    group: vmail
    mode: 0755

- name: Ensure directory for trace logs of global Sieve scripts exists
  file:
    path: /srv/mail/.sieve/logs
    state: directory
    owner: vmail
    group: vmail
    mode: 0700

# We do not need to compile the scripts or to remove the compilation,
# as they are compiled automatically on demand:
# > Debug: sieve: file script: Sieve binary `/srv/mail/.sieve/learn-spam.svbin' is not newer than the Sieve script `/srv/mail/.sieve/learn-spam.sieve'
# > Debug: sieve: binary up-to-date: script metadata indicates that binary /srv/mail/.sieve/learn-spam.svbin is not up-to-date
# > Debug: sieve: Script binary /srv/mail/.sieve/learn-spam.svbin is not up-to-date
# > Debug: sieve: Script `learn-spam' from /srv/mail/.sieve/learn-spam.sieve successfully compiled
- name: Copy global Sieve scripts
  copy:
    src: srv/mail/.sieve/
    dest: /srv/mail/.sieve/
    owner: vmail
    group: vmail
    mode: 0644

- name: Ensure rspamc to be executabled by Sieve scripts
  file:
    src: /usr/bin/rspamc
    dest: /srv/mail/.sieve/bin/rspamc
    state: link