---
- name: Ensure openSUSE will not override our config (see /usr/sbin/config.postfix)
  block:
    - ansible.builtin.lineinfile: # noqa: name[missing]
        path: /etc/sysconfig/mail
        regexp: ^MAIL_CREATE_CONFIG=
        line: MAIL_CREATE_CONFIG="no"
    - ansible.builtin.copy: # noqa: name[missing]
        # see /etc/postfix/system/config_postfix, which is called by /usr/lib/systemd/system/postfix.service
        dest: /var/adm/postfix.configured
        content: ""
        mode: "0644"
        force: false

# see /etc/postfix/system/update_postmaps, which is called by /usr/lib/systemd/system/postfix.service
- name: Ensure the maps will be only updated by ansible and not by openSUSE
  ansible.builtin.lineinfile:
    path: /etc/sysconfig/postfix
    regexp: ^POSTFIX_UPDATE_MAPS=
    line: POSTFIX_UPDATE_MAPS="no"

- name: Configure Postfix
  ansible.builtin.template:
    src: etc/postfix/main.cf.j2
    dest: /etc/postfix/main.cf
    mode: "0644"
  notify:
    - restart postfix

- name: Configure Postfix (master.cf)
  ansible.builtin.copy:
    src: etc/postfix/master.cf
    dest: /etc/postfix/master.cf
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart postfix

- name: Generate Diffie-Hellman parameters for non-export ciphers (4096 bit)
  ansible.builtin.command: >-
    openssl dhparam{{ ' -dsaparam' if not (mail_ssl.generate_safe_primes_for_dh | default(true) | bool) else '' }}
    -out /etc/postfix/dh_4096.pem 4096
  args:
    creates: /etc/postfix/dh_4096.pem

- name: Generate Diffie-Hellman parameters for export ciphers (512 bit)
  ansible.builtin.command: >-
    openssl dhparam{{ ' -dsaparam' if not (mail_ssl.generate_safe_primes_for_dh | default(true) | bool) else '' }}
    -out /etc/postfix/dh_512.pem 512
  args:
    creates: /etc/postfix/dh_512.pem

- name: Ensure file permissions of generated Diffie-Hellman parameters 
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: "0400"
  with_items:
    - /etc/postfix/dh_4096.pem
    - /etc/postfix/dh_512.pem

- name: Ensure user postfix is member of group _rspamd, so /var/run/rspamd/worker-proxy.socket can be accessed
  ansible.builtin.user:
    name: postfix
    groups: _rspamd
    append: true

- name: Configure virtual aliases
  ansible.builtin.template:
    src: etc/postfix/virtual_aliases.j2
    dest: /etc/postfix/virtual_aliases
    mode: "0600"
  notify:
    - postmap virtual_aliases

- name: Configure virtual mailboxes
  ansible.builtin.template:
    src: etc/postfix/virtual_mailboxes.j2
    dest: /etc/postfix/virtual_mailboxes
    mode: "0600"
  notify:
    - postmap virtual_mailboxes

- name: Configure transports map
  ansible.builtin.template:
    src: etc/postfix/transport.j2
    dest: /etc/postfix/transport
    mode: "0600"
  notify:
    - postmap transport

- name: Configure recipient restrictions map
  ansible.builtin.template:
    src: etc/postfix/recipient_restrictions.j2
    dest: /etc/postfix/recipient_restrictions
    mode: "0600"
  notify:
    - postmap recipient_restrictions

- name: Check if postfix /etc/postfix/access.lmdb exists
  ansible.builtin.stat:
    path: /etc/postfix/access.lmdb
  register: access_file

- name: Trigger postmap handler for /etc/postfix/access.lmdb
  debug:
    msg: "Triggering postmap for /etc/postfix/access.lmdb"
  changed_when: true
  notify:
    - postmap access
  when: not access_file.stat.exists

- name: Check if postfix /etc/aliases.lmdb exists
  ansible.builtin.stat:
    path: /etc/aliases.lmdb
  register: aliases_file

- name: Trigger postmap handler for /etc/aliases.lmdb
  debug:
    msg: "Triggering postmap for /etc/aliases.lmdb"
  changed_when: true
  notify:
    - postmap aliases
  when: not aliases_file.stat.exists

- name: Configure header checks
  ansible.builtin.template:
    src: etc/postfix/header_checks.j2
    dest: /etc/postfix/header_checks
    mode: "0600"
  notify:
    - restart postfix