---
- name: Generate Diffie-Hellman parameters
  ansible.builtin.command: openssl dhparam{{ ' -dsaparam' if not (mail_ssl.generate_safe_primes_for_dh | default(true) | bool) else '' }} -out /etc/dovecot/dh.pem
    4096
  args:
    creates: /etc/dovecot/dh.pem

- name: Configure dovecot
  ansible.builtin.template:
    src: etc/dovecot/dovecot.conf.j2
    dest: /etc/dovecot/dovecot.conf
    mode: "0640"
  notify:
    - restart dovecot

- name: Configure accounts
  ansible.builtin.template:
    src: etc/dovecot/shadow.j2
    dest: /etc/dovecot/shadow
    owner: dovecot
    group: root
    mode: "0400"

- name: Configure mailboxes
  ansible.builtin.template:
    src: etc/dovecot/users.j2
    dest: /etc/dovecot/users
    owner: dovecot
    group: root
    mode: "0400"

- name: Ensure that required mailboxes exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: vmail
    group: vmail
    mode: "0700"
  with_items:
    - "{{ mail_mailboxes | map(attribute='path') | list | unique }}"

- name: Enable dovecot and make sure it is running
  ansible.builtin.systemd:
    name: dovecot
    enabled: true
    state: started
