# -*- mode: ruby -*-
# vi: set ft=ruby :

# Because of https://github.com/hashicorp/vagrant/pull/11100
Vagrant.require_version ">= 2.2.6"

Vagrant.configure("2") do |config|    

    config.vm.box = "Leap-15.1.x86_64"
    config.vm.box_url = "https://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/openSUSE-Leap-15.1/images/boxes/Leap-15.1.x86_64.json"
    
    config.vm.synced_folder '.', '/vagrant', disabled: true

    config.vm.provider "virtualbox" do |vb|
        vb.linked_clone = true
        vb.auto_nat_dns_proxy = false
        vb.customize ["modifyvm", :id, "--audio", "none"]
    end

    # VMs:

    config.vm.define "ns" do |ns|
        ns.vm.hostname = "ns.test"
        ns.vm.network "private_network", ip: "10.0.3.2"
        ns.vm.provision "ansible" do |ansible|
            ansible.compatibility_mode = "2.0"
            ansible.verbose = false
            ansible.playbook = "testfixtures/vms/nameserver.yml"
        end
    end

    config.vm.define "sut" do |sut|
        sut.vm.hostname = "sut.mydomain.test"
        sut.vm.network "private_network", ip: "10.0.3.10"
        sut.vm.provision "ansible" do |ansible|
            ansible.compatibility_mode = "2.0"
            ansible.verbose = false
            ansible.playbook = "testfixtures/vms/sut.yml"
        end
        sut.vm.provider "virtualbox" do |vb|
            vb.memory = 2048
        end

    end

    config.vm.define "client" do |client|
        client.vm.hostname = "client.localdomain" # doens't match the DNS-RR by purpose
        client.vm.network "private_network", ip: "10.0.3.201"
        client.vm.provision "ansible" do |ansible|
            ansible.compatibility_mode = "2.0"
            ansible.verbose = false
            ansible.playbook = "testfixtures/vms/client.yml"
        end
    end

    config.vm.define "mail-sink" do |mailsink|
        mailsink.vm.hostname = "mail-sink.theirdomain.test"
        mailsink.vm.network "private_network", ip: "10.0.3.20"
        mailsink.vm.provision "ansible" do |ansible|
            ansible.compatibility_mode = "2.0"
            ansible.verbose = false
            ansible.playbook = "testfixtures/vms/mail-sink.yml"
        end
    end

end
