# -*- mode: ruby -*-
# vi: set ft=ruby :

# Because of https://github.com/hashicorp/vagrant/pull/11100
Vagrant.require_version ">= 2.2.6"

Vagrant.configure("2") do |config|    

    config.vm.provider "virtualbox" do |vb|
        vb.linked_clone = true
        vb.auto_nat_dns_proxy = false
    end
    
    config.vm.define "ns" do |sut|
        sut.vm.box = "Leap-15.1.x86_64"
        sut.vm.box_url = "https://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/openSUSE-Leap-15.1/images/boxes/Leap-15.1.x86_64.json"
        sut.vm.hostname = "ns.test"
        sut.vm.network "private_network", ip: "10.0.3.2"
        sut.vm.provision :ansible do |ansible|
            ansible.force_remote_user = true
            ansible.compatibility_mode = "2.0"
            ansible.verbose = true
            ansible.playbook = "testfixtures/vms/nameserver.yml"
        end
    end

    config.vm.define "sut" do |sut|
        sut.vm.box = "Leap-15.1.x86_64"
        sut.vm.box_url = "https://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/openSUSE-Leap-15.1/images/boxes/Leap-15.1.x86_64.json"
        sut.vm.hostname = "sut.mydomain.test"
        sut.vm.network "private_network", ip: "10.0.3.10"
        sut.vm.provision :ansible do |ansible|
            ansible.compatibility_mode = "2.0"
            ansible.verbose = true
            ansible.playbook = "testfixtures/vms/sut.yml"
        end
        sut.vm.provider "virtualbox" do |vb|
            vb.memory = 2048
        end
    end

    config.vm.define "client" do |sut|
        sut.vm.box = "Leap-15.1.x86_64"
        sut.vm.box_url = "https://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/openSUSE-Leap-15.1/images/boxes/Leap-15.1.x86_64.json"
        sut.vm.hostname = "client.localdomain" # doens't match the DNS-RR by purpose
        sut.vm.network "private_network", ip: "10.0.3.201"
        sut.vm.provision :ansible do |ansible|
            ansible.compatibility_mode = "2.0"
            ansible.verbose = true
            ansible.playbook = "testfixtures/vms/client.yml"
        end
    end

    config.vm.define "mail-sink" do |sut|
        sut.vm.box = "Leap-15.1.x86_64"
        sut.vm.box_url = "https://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/openSUSE-Leap-15.1/images/boxes/Leap-15.1.x86_64.json"
        sut.vm.hostname = "mail-sink.theirdomain.test"
        sut.vm.network "private_network", ip: "10.0.3.20"
        sut.vm.provision :ansible do |ansible|
            ansible.compatibility_mode = "2.0"
            ansible.verbose = true
            ansible.playbook = "testfixtures/vms/mail-sink.yml"
        end
    end

end
