---

- name: restart redis
  systemd: name=redis@rspamd state=restarted

- name: restart rspamd
  systemd: name=rspamd state=restarted

- name: restart dovecot
  systemd: name=dovecot state=restarted

- name: restart postfix
  systemd: name=postfix state=restarted

- name: restart apparmor
  systemd: name=apparmor state=restarted

- name: postmap virtual_aliases
  command: postmap lmdb:/etc/postfix/virtual_aliases
  notify: restart postfix

- name: postmap virtual_mailboxes
  command: postmap lmdb:/etc/postfix/virtual_mailboxes
  notify: restart postfix

- name: postmap transport
  command: postmap lmdb:/etc/postfix/transport
  notify: restart postfix

- name: postmap recipient_restrictions
  command: postmap lmdb:/etc/postfix/recipient_restrictions
  notify: restart postfix

- name: print error_messages
  debug:
    var: error_messages
  failed_when: True

- name: print everything alright
  debug:
    msg: Nothing special happened during the configuration. The mailserver should work properly.
