---

- name: restart redis # noqa: name[casing]
  ansible.builtin.systemd:
    name: redis@rspamd
    state: restarted

- name: restart rspamd # noqa: name[casing]
  ansible.builtin.systemd:
    name: rspamd
    state: restarted

- name: restart dovecot # noqa: name[casing]
  ansible.builtin.systemd:
    name: dovecot
    state: restarted

- name: restart postfix # noqa: name[casing]
  ansible.builtin.systemd:
    name: postfix
    state: restarted

- name: restart apparmor # noqa: name[casing]
  ansible.builtin.systemd:
    name: apparmor
    state: restarted

- name: postmap virtual_aliases # noqa: name[casing]
  ansible.builtin.command: postmap lmdb:/etc/postfix/virtual_aliases
  changed_when: true
  notify: restart postfix

- name: postmap virtual_mailboxes # noqa: name[casing]
  ansible.builtin.command: postmap lmdb:/etc/postfix/virtual_mailboxes
  changed_when: true
  notify: restart postfix

- name: postmap transport # noqa: name[casing]
  ansible.builtin.command: postmap lmdb:/etc/postfix/transport
  changed_when: true
  notify: restart postfix

- name: postmap recipient_restrictions # noqa: name[casing]
  ansible.builtin.command: postmap lmdb:/etc/postfix/recipient_restrictions
  changed_when: true
  notify: restart postfix

- name: postmap access # noqa: name[casing]
  ansible.builtin.command: postmap lmdb:/etc/postfix/access
  changed_when: true
  notify: restart postfix

- name: postmap aliases # noqa: name[casing]
  ansible.builtin.command: postmap lmdb:/etc/aliases
  changed_when: true
  notify: restart postfix

- name: print error_messages # noqa: name[casing]
  ansible.builtin.debug:
    var: error_messages
  failed_when: true

- name: print everything alright # noqa: name[casing]
  ansible.builtin.debug:
    msg: Nothing special happened during the configuration. The mailserver should work properly.
