---

- name: Install python-xml needed for ansible's zypper module
  command: /usr/bin/zypper --non-interactive --quiet install python-xml
  args:
    warn: no
  changed_when: false
  warn: False

- name: Install common packages
  zypper:
    name: "{{ item }}"
    state: present
  with_items:
    - command-not-found
    - htop
    - man
