---

- name: restart redis
  systemd: name=redis@rspamd state=restarted

- name: restart rspamd
  systemd: name=rspamd state=restarted

- name: restart dovecot
  systemd: name=dovecot state=restarted

- name: postmap virtual_aliases
  command: postmap hash:/etc/postfix/virtual_aliases

- name: postmap virtual_mailboxes
  command: postmap hash:/etc/postfix/virtual_mailboxes