name: Run tests against latest openSUSE Leap 15.2

on: 
  push:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: macos-10.15
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Vagrant boxes
      uses: actions/cache@v2
      with:
        path: ~/.vagrant.d/boxes
    
    - name: Show Vagrant version
      run: vagrant --version

    - name: Install pipenv
      run: pip install pipenv

    - name: Install required (and locked) dependecies with pipenv
      run: pipenv install --dev
    
    - name: Ensure to use the latest boxes
      run: vagrant box update
      working-directory: tests

    - name: Prepare Vagrant test environment
      run: make -j setup
      working-directory: tests
    
    - name: Run tests
      run: make -k tests
      working-directory: tests

    - name: Gather facts
      run: |
        pip list
        vagrant ssh -c "ip addr show" ns
        vagrant ssh -c "ip addr show" sut
        vagrant ssh -c "ip addr show" client
        vagrant ssh -c "ip addr show" mail-sink
        vagrant ssh -c "dig mydomain.test MX" client
        vagrant ssh -c "ping -c 3 10.0.3.10" client
        vagrant ssh -c "sudo journalctl --no-pager -n 50 -u named" ns
        vagrant ssh -c "systemctl --no-page list-units --type=service" sut
        vagrant ssh -c "sudo journalctl --no-pager -n 50 -u clamd" sut
        vagrant ssh -c "sudo journalctl --no-pager -n 50 -u postfix" sut
        vagrant ssh -c "sudo journalctl --no-pager -n 50 -u rspamd" sut
        vagrant ssh -c "sudo journalctl --no-pager -n 50 -u dovecot" sut
      working-directory: tests
